In [1]:
import numpy as np


In [11]:
import sys
assert sys.version_info>=(3,5)

In [8]:
import tensorflow as tf
from tensorflow import keras 
import pandas as pd

In [10]:
dataset=pd.read_csv("Churn_Modelling.csv")

In [13]:
X=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [14]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [15]:
print(y)

[1 0 1 ... 1 1 0]


In [21]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [22]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])],remainder='passthrough' )
X=np.array(ct.fit_transform(X))

In [31]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y, test_size=.2, random_state=0)

In [41]:
from sklearn.model_selection import train_test_split
X_train,x_test,y_train,y_test= train_test_split(X,y,test_size=.2, random_state=0)


In [43]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)


In [47]:
ann=tf.keras.models.Sequential()

In [50]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [52]:
ann.add(tf.keras.layers.Dense(units=12,activation='relu'))

In [53]:
ann.add(tf.keras.layers.Dense(units=1,activation='sigmoid'))

In [57]:
ann.compile(optimizer='adam',loss='binary_crossentropy', metrics=['accuracy'])

In [58]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 420us/step - accuracy: 0.7954 - loss: 0.5662
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 417us/step - accuracy: 0.7950 - loss: 0.4409
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 396us/step - accuracy: 0.7999 - loss: 0.4325
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 389us/step - accuracy: 0.8088 - loss: 0.4280
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8117 - loss: 0.4134
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 376us/step - accuracy: 0.8159 - loss: 0.4217
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 450us/step - accuracy: 0.8221 - loss: 0.4168
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 385us/step - accuracy: 0.8310 - loss: 0.4000
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 410us/step - accuracy: 0.8314 - loss: 0.3916
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 411us/step - accuracy: 0.8514 - loss: 0.3660
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 472us/step - accuracy: 0.8490 - loss: 0.3656
Epoch 12/100
250/25

In [59]:
ann.fit(X_train,y_train,batch_size=32,epochs=100)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 685us/step - accuracy: 0.8660 - loss: 0.3270
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 399us/step - accuracy: 0.8690 - loss: 0.3238
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 391us/step - accuracy: 0.8635 - loss: 0.3310
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 390us/step - accuracy: 0.8633 - loss: 0.3372
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - accuracy: 0.8677 - loss: 0.3253
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 386us/step - accuracy: 0.8649 - loss: 0.3334
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 402us/step - accuracy: 0.8661 - loss: 0.3270
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 397us/step - accuracy: 0.8688 - loss: 0.3297
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 412us/step - accuracy: 0.8637 - loss: 0.3207
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 418us/step - accuracy: 0.8653 - loss: 0.3318
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 0s 387us/step - accuracy: 0.8688 - loss: 0.3303
Epoch 12/100
250/25

In [62]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,6000,2,1,1,5000]]))>.5)


1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step
[[False]]


In [65]:
y_pred=ann.predict(X_test)
y_pred=(y_pred>.5)
print()

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 357us/step



In [67]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
accuracy_score(y_test,y_pred)


0.8635

In [68]:
print(cm)

[[1539   56]
 [ 217  188]]


In [69]:
def n():
    return (34)


